"""Add cascade delete

Revision ID: 361a50259a99
Revises: c228b3cadacf
Create Date: 2025-03-18 16:32:51.877473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '361a50259a99'
down_revision: Union[str, None] = 'c228b3cadacf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('materials_message_id_fkey', 'materials', type_='foreignkey')
    op.create_foreign_key(None, 'materials', 'messages', ['message_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('questions_test_id_fkey', 'questions', type_='foreignkey')
    op.create_foreign_key(None, 'questions', 'tests', ['test_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('tests_message_id_fkey', 'tests', type_='foreignkey')
    op.create_foreign_key(None, 'tests', 'messages', ['message_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tests', type_='foreignkey')
    op.create_foreign_key('tests_message_id_fkey', 'tests', 'messages', ['message_id'], ['id'])
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.create_foreign_key('questions_test_id_fkey', 'questions', 'tests', ['test_id'], ['id'])
    op.drop_constraint(None, 'materials', type_='foreignkey')
    op.create_foreign_key('materials_message_id_fkey', 'materials', 'messages', ['message_id'], ['id'])
    # ### end Alembic commands ###
