"""Fix question.

Revision ID: 4d6bb8e6922d
Revises: 9f5050418a02
Create Date: 2024-11-12 01:28:05.144150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d6bb8e6922d'
down_revision: Union[str, None] = '9f5050418a02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('questions_message_id_fkey', 'questions', type_='foreignkey')
    op.drop_column('questions', 'message_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('message_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.create_foreign_key('questions_message_id_fkey', 'questions', 'messages', ['message_id'], ['id'])
    # ### end Alembic commands ###
