"""update user 2

Revision ID: 5f156a28ed9b
Revises: 8746c18e8036
Create Date: 2024-10-28 21:41:03.347473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f156a28ed9b'
down_revision: Union[str, None] = '8746c18e8036'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_sso_type_fkey', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'sso_providers', ['sso_type'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('users_sso_type_fkey', 'users', 'users', ['sso_type'], ['id'])
    # ### end Alembic commands ###
