"""change question message_id to test_id

Revision ID: 9f5050418a02
Revises: 2098a45e315d
Create Date: 2024-11-11 23:51:58.586035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f5050418a02'
down_revision: Union[str, None] = '2098a45e315d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('test_id', sa.BigInteger(), nullable=False))
    op.create_foreign_key(None, 'questions', 'tests', ['test_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.drop_column('questions', 'test_id')
    # ### end Alembic commands ###
